apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: celeries.example.com
spec:
  group: example.com
  names:
    kind: Celery
    listKind: CeleryList
    plural: celeries
    singular: celery
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Celery is the Schema for the celeries API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CelerySpec defines the desired state of Celery
          properties:
            brokerImage:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            frontendImage:
              type: string
            wSize:
              format: int32
              type: integer
            workerImage:
              type: string
          required:
          - brokerImage
          - frontendImage
          - wSize
          - workerImage
          type: object
        status:
          description: CeleryStatus defines the observed state of Celery
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
